// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCourseUsers(t *testing.T) {
	t.Parallel()

	query := CourseUsers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCourseUsersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCourseUsersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CourseUsers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCourseUsersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CourseUserSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCourseUsersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CourseUserExists(ctx, tx, o.CourseID, o.UserID)
	if err != nil {
		t.Errorf("Unable to check if CourseUser exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CourseUserExists to return true, but got false.")
	}
}

func testCourseUsersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	courseUserFound, err := FindCourseUser(ctx, tx, o.CourseID, o.UserID)
	if err != nil {
		t.Error(err)
	}

	if courseUserFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCourseUsersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CourseUsers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCourseUsersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CourseUsers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCourseUsersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	courseUserOne := &CourseUser{}
	courseUserTwo := &CourseUser{}
	if err = randomize.Struct(seed, courseUserOne, courseUserDBTypes, false, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}
	if err = randomize.Struct(seed, courseUserTwo, courseUserDBTypes, false, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = courseUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = courseUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CourseUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCourseUsersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	courseUserOne := &CourseUser{}
	courseUserTwo := &CourseUser{}
	if err = randomize.Struct(seed, courseUserOne, courseUserDBTypes, false, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}
	if err = randomize.Struct(seed, courseUserTwo, courseUserDBTypes, false, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = courseUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = courseUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func courseUserBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *CourseUser) error {
	*o = CourseUser{}
	return nil
}

func courseUserAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *CourseUser) error {
	*o = CourseUser{}
	return nil
}

func courseUserAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *CourseUser) error {
	*o = CourseUser{}
	return nil
}

func courseUserBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CourseUser) error {
	*o = CourseUser{}
	return nil
}

func courseUserAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CourseUser) error {
	*o = CourseUser{}
	return nil
}

func courseUserBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CourseUser) error {
	*o = CourseUser{}
	return nil
}

func courseUserAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CourseUser) error {
	*o = CourseUser{}
	return nil
}

func courseUserBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CourseUser) error {
	*o = CourseUser{}
	return nil
}

func courseUserAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CourseUser) error {
	*o = CourseUser{}
	return nil
}

func testCourseUsersHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &CourseUser{}
	o := &CourseUser{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, courseUserDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CourseUser object: %s", err)
	}

	AddCourseUserHook(boil.BeforeInsertHook, courseUserBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	courseUserBeforeInsertHooks = []CourseUserHook{}

	AddCourseUserHook(boil.AfterInsertHook, courseUserAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	courseUserAfterInsertHooks = []CourseUserHook{}

	AddCourseUserHook(boil.AfterSelectHook, courseUserAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	courseUserAfterSelectHooks = []CourseUserHook{}

	AddCourseUserHook(boil.BeforeUpdateHook, courseUserBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	courseUserBeforeUpdateHooks = []CourseUserHook{}

	AddCourseUserHook(boil.AfterUpdateHook, courseUserAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	courseUserAfterUpdateHooks = []CourseUserHook{}

	AddCourseUserHook(boil.BeforeDeleteHook, courseUserBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	courseUserBeforeDeleteHooks = []CourseUserHook{}

	AddCourseUserHook(boil.AfterDeleteHook, courseUserAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	courseUserAfterDeleteHooks = []CourseUserHook{}

	AddCourseUserHook(boil.BeforeUpsertHook, courseUserBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	courseUserBeforeUpsertHooks = []CourseUserHook{}

	AddCourseUserHook(boil.AfterUpsertHook, courseUserAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	courseUserAfterUpsertHooks = []CourseUserHook{}
}

func testCourseUsersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCourseUsersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(courseUserColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCourseUserToOneCourseUsingCourse(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local CourseUser
	var foreign Course

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, courseUserDBTypes, false, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, courseDBTypes, false, courseColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Course struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.CourseID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Course().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := CourseUserSlice{&local}
	if err = local.L.LoadCourse(ctx, tx, false, (*[]*CourseUser)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Course == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Course = nil
	if err = local.L.LoadCourse(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Course == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testCourseUserToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local CourseUser
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, courseUserDBTypes, false, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := CourseUserSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*CourseUser)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testCourseUserToOneSetOpCourseUsingCourse(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CourseUser
	var b, c Course

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, courseUserDBTypes, false, strmangle.SetComplement(courseUserPrimaryKeyColumns, courseUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, courseDBTypes, false, strmangle.SetComplement(coursePrimaryKeyColumns, courseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, courseDBTypes, false, strmangle.SetComplement(coursePrimaryKeyColumns, courseColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Course{&b, &c} {
		err = a.SetCourse(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Course != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.CourseUsers[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.CourseID != x.ID {
			t.Error("foreign key was wrong value", a.CourseID)
		}

		if exists, err := CourseUserExists(ctx, tx, a.CourseID, a.UserID); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}
func testCourseUserToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CourseUser
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, courseUserDBTypes, false, strmangle.SetComplement(courseUserPrimaryKeyColumns, courseUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.CourseUsers[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		if exists, err := CourseUserExists(ctx, tx, a.CourseID, a.UserID); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testCourseUsersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCourseUsersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CourseUserSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCourseUsersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CourseUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	courseUserDBTypes = map[string]string{`CourseID`: `integer`, `UserID`: `integer`, `Role`: `integer`}
	_                 = bytes.MinRead
)

func testCourseUsersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(courseUserPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(courseUserAllColumns) == len(courseUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCourseUsersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(courseUserAllColumns) == len(courseUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CourseUser{}
	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, courseUserDBTypes, true, courseUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(courseUserAllColumns, courseUserPrimaryKeyColumns) {
		fields = courseUserAllColumns
	} else {
		fields = strmangle.SetComplement(
			courseUserAllColumns,
			courseUserPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CourseUserSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCourseUsersUpsert(t *testing.T) {
	t.Parallel()

	if len(courseUserAllColumns) == len(courseUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CourseUser{}
	if err = randomize.Struct(seed, &o, courseUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CourseUser: %s", err)
	}

	count, err := CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, courseUserDBTypes, false, courseUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CourseUser struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CourseUser: %s", err)
	}

	count, err = CourseUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
