// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testHomeworkSubmissionComments(t *testing.T) {
	t.Parallel()

	query := HomeworkSubmissionComments()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testHomeworkSubmissionCommentsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHomeworkSubmissionCommentsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := HomeworkSubmissionComments().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHomeworkSubmissionCommentsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := HomeworkSubmissionCommentSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHomeworkSubmissionCommentsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := HomeworkSubmissionCommentExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if HomeworkSubmissionComment exists: %s", err)
	}
	if !e {
		t.Errorf("Expected HomeworkSubmissionCommentExists to return true, but got false.")
	}
}

func testHomeworkSubmissionCommentsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	homeworkSubmissionCommentFound, err := FindHomeworkSubmissionComment(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if homeworkSubmissionCommentFound == nil {
		t.Error("want a record, got nil")
	}
}

func testHomeworkSubmissionCommentsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = HomeworkSubmissionComments().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testHomeworkSubmissionCommentsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := HomeworkSubmissionComments().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testHomeworkSubmissionCommentsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	homeworkSubmissionCommentOne := &HomeworkSubmissionComment{}
	homeworkSubmissionCommentTwo := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, homeworkSubmissionCommentOne, homeworkSubmissionCommentDBTypes, false, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}
	if err = randomize.Struct(seed, homeworkSubmissionCommentTwo, homeworkSubmissionCommentDBTypes, false, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = homeworkSubmissionCommentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = homeworkSubmissionCommentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := HomeworkSubmissionComments().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testHomeworkSubmissionCommentsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	homeworkSubmissionCommentOne := &HomeworkSubmissionComment{}
	homeworkSubmissionCommentTwo := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, homeworkSubmissionCommentOne, homeworkSubmissionCommentDBTypes, false, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}
	if err = randomize.Struct(seed, homeworkSubmissionCommentTwo, homeworkSubmissionCommentDBTypes, false, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = homeworkSubmissionCommentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = homeworkSubmissionCommentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func homeworkSubmissionCommentBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *HomeworkSubmissionComment) error {
	*o = HomeworkSubmissionComment{}
	return nil
}

func homeworkSubmissionCommentAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *HomeworkSubmissionComment) error {
	*o = HomeworkSubmissionComment{}
	return nil
}

func homeworkSubmissionCommentAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *HomeworkSubmissionComment) error {
	*o = HomeworkSubmissionComment{}
	return nil
}

func homeworkSubmissionCommentBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *HomeworkSubmissionComment) error {
	*o = HomeworkSubmissionComment{}
	return nil
}

func homeworkSubmissionCommentAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *HomeworkSubmissionComment) error {
	*o = HomeworkSubmissionComment{}
	return nil
}

func homeworkSubmissionCommentBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *HomeworkSubmissionComment) error {
	*o = HomeworkSubmissionComment{}
	return nil
}

func homeworkSubmissionCommentAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *HomeworkSubmissionComment) error {
	*o = HomeworkSubmissionComment{}
	return nil
}

func homeworkSubmissionCommentBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *HomeworkSubmissionComment) error {
	*o = HomeworkSubmissionComment{}
	return nil
}

func homeworkSubmissionCommentAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *HomeworkSubmissionComment) error {
	*o = HomeworkSubmissionComment{}
	return nil
}

func testHomeworkSubmissionCommentsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &HomeworkSubmissionComment{}
	o := &HomeworkSubmissionComment{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, false); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment object: %s", err)
	}

	AddHomeworkSubmissionCommentHook(boil.BeforeInsertHook, homeworkSubmissionCommentBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	homeworkSubmissionCommentBeforeInsertHooks = []HomeworkSubmissionCommentHook{}

	AddHomeworkSubmissionCommentHook(boil.AfterInsertHook, homeworkSubmissionCommentAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	homeworkSubmissionCommentAfterInsertHooks = []HomeworkSubmissionCommentHook{}

	AddHomeworkSubmissionCommentHook(boil.AfterSelectHook, homeworkSubmissionCommentAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	homeworkSubmissionCommentAfterSelectHooks = []HomeworkSubmissionCommentHook{}

	AddHomeworkSubmissionCommentHook(boil.BeforeUpdateHook, homeworkSubmissionCommentBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	homeworkSubmissionCommentBeforeUpdateHooks = []HomeworkSubmissionCommentHook{}

	AddHomeworkSubmissionCommentHook(boil.AfterUpdateHook, homeworkSubmissionCommentAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	homeworkSubmissionCommentAfterUpdateHooks = []HomeworkSubmissionCommentHook{}

	AddHomeworkSubmissionCommentHook(boil.BeforeDeleteHook, homeworkSubmissionCommentBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	homeworkSubmissionCommentBeforeDeleteHooks = []HomeworkSubmissionCommentHook{}

	AddHomeworkSubmissionCommentHook(boil.AfterDeleteHook, homeworkSubmissionCommentAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	homeworkSubmissionCommentAfterDeleteHooks = []HomeworkSubmissionCommentHook{}

	AddHomeworkSubmissionCommentHook(boil.BeforeUpsertHook, homeworkSubmissionCommentBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	homeworkSubmissionCommentBeforeUpsertHooks = []HomeworkSubmissionCommentHook{}

	AddHomeworkSubmissionCommentHook(boil.AfterUpsertHook, homeworkSubmissionCommentAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	homeworkSubmissionCommentAfterUpsertHooks = []HomeworkSubmissionCommentHook{}
}

func testHomeworkSubmissionCommentsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testHomeworkSubmissionCommentsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(homeworkSubmissionCommentColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testHomeworkSubmissionCommentToOneHomeworkSubmissionUsingHomeworkSubmission(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local HomeworkSubmissionComment
	var foreign HomeworkSubmission

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, homeworkSubmissionCommentDBTypes, false, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, homeworkSubmissionDBTypes, false, homeworkSubmissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmission struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.HomeworkSubmissionID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.HomeworkSubmission().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := HomeworkSubmissionCommentSlice{&local}
	if err = local.L.LoadHomeworkSubmission(ctx, tx, false, (*[]*HomeworkSubmissionComment)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.HomeworkSubmission == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.HomeworkSubmission = nil
	if err = local.L.LoadHomeworkSubmission(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.HomeworkSubmission == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testHomeworkSubmissionCommentToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local HomeworkSubmissionComment
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, homeworkSubmissionCommentDBTypes, false, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := HomeworkSubmissionCommentSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*HomeworkSubmissionComment)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testHomeworkSubmissionCommentToOneSetOpHomeworkSubmissionUsingHomeworkSubmission(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a HomeworkSubmissionComment
	var b, c HomeworkSubmission

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, homeworkSubmissionCommentDBTypes, false, strmangle.SetComplement(homeworkSubmissionCommentPrimaryKeyColumns, homeworkSubmissionCommentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, homeworkSubmissionDBTypes, false, strmangle.SetComplement(homeworkSubmissionPrimaryKeyColumns, homeworkSubmissionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, homeworkSubmissionDBTypes, false, strmangle.SetComplement(homeworkSubmissionPrimaryKeyColumns, homeworkSubmissionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*HomeworkSubmission{&b, &c} {
		err = a.SetHomeworkSubmission(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.HomeworkSubmission != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.HomeworkSubmissionComments[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.HomeworkSubmissionID != x.ID {
			t.Error("foreign key was wrong value", a.HomeworkSubmissionID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.HomeworkSubmissionID))
		reflect.Indirect(reflect.ValueOf(&a.HomeworkSubmissionID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.HomeworkSubmissionID != x.ID {
			t.Error("foreign key was wrong value", a.HomeworkSubmissionID, x.ID)
		}
	}
}
func testHomeworkSubmissionCommentToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a HomeworkSubmissionComment
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, homeworkSubmissionCommentDBTypes, false, strmangle.SetComplement(homeworkSubmissionCommentPrimaryKeyColumns, homeworkSubmissionCommentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.HomeworkSubmissionComments[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testHomeworkSubmissionCommentsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testHomeworkSubmissionCommentsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := HomeworkSubmissionCommentSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testHomeworkSubmissionCommentsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := HomeworkSubmissionComments().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	homeworkSubmissionCommentDBTypes = map[string]string{`ID`: `integer`, `HomeworkSubmissionID`: `integer`, `UserID`: `integer`, `Comment`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                                = bytes.MinRead
)

func testHomeworkSubmissionCommentsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(homeworkSubmissionCommentPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(homeworkSubmissionCommentAllColumns) == len(homeworkSubmissionCommentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testHomeworkSubmissionCommentsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(homeworkSubmissionCommentAllColumns) == len(homeworkSubmissionCommentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, homeworkSubmissionCommentDBTypes, true, homeworkSubmissionCommentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(homeworkSubmissionCommentAllColumns, homeworkSubmissionCommentPrimaryKeyColumns) {
		fields = homeworkSubmissionCommentAllColumns
	} else {
		fields = strmangle.SetComplement(
			homeworkSubmissionCommentAllColumns,
			homeworkSubmissionCommentPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := HomeworkSubmissionCommentSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testHomeworkSubmissionCommentsUpsert(t *testing.T) {
	t.Parallel()

	if len(homeworkSubmissionCommentAllColumns) == len(homeworkSubmissionCommentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := HomeworkSubmissionComment{}
	if err = randomize.Struct(seed, &o, homeworkSubmissionCommentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert HomeworkSubmissionComment: %s", err)
	}

	count, err := HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, homeworkSubmissionCommentDBTypes, false, homeworkSubmissionCommentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize HomeworkSubmissionComment struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert HomeworkSubmissionComment: %s", err)
	}

	count, err = HomeworkSubmissionComments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
