// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// HomeworkSubmissionComment is an object representing the database table.
type HomeworkSubmissionComment struct {
	ID                   int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	HomeworkSubmissionID int       `boil:"homework_submission_id" json:"homework_submission_id" toml:"homework_submission_id" yaml:"homework_submission_id"`
	UserID               int       `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Comment              string    `boil:"comment" json:"comment" toml:"comment" yaml:"comment"`
	CreatedAt            time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt            time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *homeworkSubmissionCommentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L homeworkSubmissionCommentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var HomeworkSubmissionCommentColumns = struct {
	ID                   string
	HomeworkSubmissionID string
	UserID               string
	Comment              string
	CreatedAt            string
	UpdatedAt            string
}{
	ID:                   "id",
	HomeworkSubmissionID: "homework_submission_id",
	UserID:               "user_id",
	Comment:              "comment",
	CreatedAt:            "created_at",
	UpdatedAt:            "updated_at",
}

var HomeworkSubmissionCommentTableColumns = struct {
	ID                   string
	HomeworkSubmissionID string
	UserID               string
	Comment              string
	CreatedAt            string
	UpdatedAt            string
}{
	ID:                   "homework_submission_comments.id",
	HomeworkSubmissionID: "homework_submission_comments.homework_submission_id",
	UserID:               "homework_submission_comments.user_id",
	Comment:              "homework_submission_comments.comment",
	CreatedAt:            "homework_submission_comments.created_at",
	UpdatedAt:            "homework_submission_comments.updated_at",
}

// Generated where

var HomeworkSubmissionCommentWhere = struct {
	ID                   whereHelperint
	HomeworkSubmissionID whereHelperint
	UserID               whereHelperint
	Comment              whereHelperstring
	CreatedAt            whereHelpertime_Time
	UpdatedAt            whereHelpertime_Time
}{
	ID:                   whereHelperint{field: "\"homework_submission_comments\".\"id\""},
	HomeworkSubmissionID: whereHelperint{field: "\"homework_submission_comments\".\"homework_submission_id\""},
	UserID:               whereHelperint{field: "\"homework_submission_comments\".\"user_id\""},
	Comment:              whereHelperstring{field: "\"homework_submission_comments\".\"comment\""},
	CreatedAt:            whereHelpertime_Time{field: "\"homework_submission_comments\".\"created_at\""},
	UpdatedAt:            whereHelpertime_Time{field: "\"homework_submission_comments\".\"updated_at\""},
}

// HomeworkSubmissionCommentRels is where relationship names are stored.
var HomeworkSubmissionCommentRels = struct {
	HomeworkSubmission string
	User               string
}{
	HomeworkSubmission: "HomeworkSubmission",
	User:               "User",
}

// homeworkSubmissionCommentR is where relationships are stored.
type homeworkSubmissionCommentR struct {
	HomeworkSubmission *HomeworkSubmission `boil:"HomeworkSubmission" json:"HomeworkSubmission" toml:"HomeworkSubmission" yaml:"HomeworkSubmission"`
	User               *User               `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*homeworkSubmissionCommentR) NewStruct() *homeworkSubmissionCommentR {
	return &homeworkSubmissionCommentR{}
}

// homeworkSubmissionCommentL is where Load methods for each relationship are stored.
type homeworkSubmissionCommentL struct{}

var (
	homeworkSubmissionCommentAllColumns            = []string{"id", "homework_submission_id", "user_id", "comment", "created_at", "updated_at"}
	homeworkSubmissionCommentColumnsWithoutDefault = []string{"homework_submission_id", "user_id", "comment", "created_at", "updated_at"}
	homeworkSubmissionCommentColumnsWithDefault    = []string{"id"}
	homeworkSubmissionCommentPrimaryKeyColumns     = []string{"id"}
)

type (
	// HomeworkSubmissionCommentSlice is an alias for a slice of pointers to HomeworkSubmissionComment.
	// This should almost always be used instead of []HomeworkSubmissionComment.
	HomeworkSubmissionCommentSlice []*HomeworkSubmissionComment
	// HomeworkSubmissionCommentHook is the signature for custom HomeworkSubmissionComment hook methods
	HomeworkSubmissionCommentHook func(context.Context, boil.ContextExecutor, *HomeworkSubmissionComment) error

	homeworkSubmissionCommentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	homeworkSubmissionCommentType                 = reflect.TypeOf(&HomeworkSubmissionComment{})
	homeworkSubmissionCommentMapping              = queries.MakeStructMapping(homeworkSubmissionCommentType)
	homeworkSubmissionCommentPrimaryKeyMapping, _ = queries.BindMapping(homeworkSubmissionCommentType, homeworkSubmissionCommentMapping, homeworkSubmissionCommentPrimaryKeyColumns)
	homeworkSubmissionCommentInsertCacheMut       sync.RWMutex
	homeworkSubmissionCommentInsertCache          = make(map[string]insertCache)
	homeworkSubmissionCommentUpdateCacheMut       sync.RWMutex
	homeworkSubmissionCommentUpdateCache          = make(map[string]updateCache)
	homeworkSubmissionCommentUpsertCacheMut       sync.RWMutex
	homeworkSubmissionCommentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var homeworkSubmissionCommentBeforeInsertHooks []HomeworkSubmissionCommentHook
var homeworkSubmissionCommentBeforeUpdateHooks []HomeworkSubmissionCommentHook
var homeworkSubmissionCommentBeforeDeleteHooks []HomeworkSubmissionCommentHook
var homeworkSubmissionCommentBeforeUpsertHooks []HomeworkSubmissionCommentHook

var homeworkSubmissionCommentAfterInsertHooks []HomeworkSubmissionCommentHook
var homeworkSubmissionCommentAfterSelectHooks []HomeworkSubmissionCommentHook
var homeworkSubmissionCommentAfterUpdateHooks []HomeworkSubmissionCommentHook
var homeworkSubmissionCommentAfterDeleteHooks []HomeworkSubmissionCommentHook
var homeworkSubmissionCommentAfterUpsertHooks []HomeworkSubmissionCommentHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *HomeworkSubmissionComment) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range homeworkSubmissionCommentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *HomeworkSubmissionComment) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range homeworkSubmissionCommentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *HomeworkSubmissionComment) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range homeworkSubmissionCommentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *HomeworkSubmissionComment) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range homeworkSubmissionCommentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *HomeworkSubmissionComment) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range homeworkSubmissionCommentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *HomeworkSubmissionComment) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range homeworkSubmissionCommentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *HomeworkSubmissionComment) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range homeworkSubmissionCommentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *HomeworkSubmissionComment) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range homeworkSubmissionCommentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *HomeworkSubmissionComment) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range homeworkSubmissionCommentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddHomeworkSubmissionCommentHook registers your hook function for all future operations.
func AddHomeworkSubmissionCommentHook(hookPoint boil.HookPoint, homeworkSubmissionCommentHook HomeworkSubmissionCommentHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		homeworkSubmissionCommentBeforeInsertHooks = append(homeworkSubmissionCommentBeforeInsertHooks, homeworkSubmissionCommentHook)
	case boil.BeforeUpdateHook:
		homeworkSubmissionCommentBeforeUpdateHooks = append(homeworkSubmissionCommentBeforeUpdateHooks, homeworkSubmissionCommentHook)
	case boil.BeforeDeleteHook:
		homeworkSubmissionCommentBeforeDeleteHooks = append(homeworkSubmissionCommentBeforeDeleteHooks, homeworkSubmissionCommentHook)
	case boil.BeforeUpsertHook:
		homeworkSubmissionCommentBeforeUpsertHooks = append(homeworkSubmissionCommentBeforeUpsertHooks, homeworkSubmissionCommentHook)
	case boil.AfterInsertHook:
		homeworkSubmissionCommentAfterInsertHooks = append(homeworkSubmissionCommentAfterInsertHooks, homeworkSubmissionCommentHook)
	case boil.AfterSelectHook:
		homeworkSubmissionCommentAfterSelectHooks = append(homeworkSubmissionCommentAfterSelectHooks, homeworkSubmissionCommentHook)
	case boil.AfterUpdateHook:
		homeworkSubmissionCommentAfterUpdateHooks = append(homeworkSubmissionCommentAfterUpdateHooks, homeworkSubmissionCommentHook)
	case boil.AfterDeleteHook:
		homeworkSubmissionCommentAfterDeleteHooks = append(homeworkSubmissionCommentAfterDeleteHooks, homeworkSubmissionCommentHook)
	case boil.AfterUpsertHook:
		homeworkSubmissionCommentAfterUpsertHooks = append(homeworkSubmissionCommentAfterUpsertHooks, homeworkSubmissionCommentHook)
	}
}

// One returns a single homeworkSubmissionComment record from the query.
func (q homeworkSubmissionCommentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*HomeworkSubmissionComment, error) {
	o := &HomeworkSubmissionComment{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for homework_submission_comments")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all HomeworkSubmissionComment records from the query.
func (q homeworkSubmissionCommentQuery) All(ctx context.Context, exec boil.ContextExecutor) (HomeworkSubmissionCommentSlice, error) {
	var o []*HomeworkSubmissionComment

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to HomeworkSubmissionComment slice")
	}

	if len(homeworkSubmissionCommentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all HomeworkSubmissionComment records in the query.
func (q homeworkSubmissionCommentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count homework_submission_comments rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q homeworkSubmissionCommentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if homework_submission_comments exists")
	}

	return count > 0, nil
}

// HomeworkSubmission pointed to by the foreign key.
func (o *HomeworkSubmissionComment) HomeworkSubmission(mods ...qm.QueryMod) homeworkSubmissionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.HomeworkSubmissionID),
	}

	queryMods = append(queryMods, mods...)

	query := HomeworkSubmissions(queryMods...)
	queries.SetFrom(query.Query, "\"homework_submissions\"")

	return query
}

// User pointed to by the foreign key.
func (o *HomeworkSubmissionComment) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// LoadHomeworkSubmission allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (homeworkSubmissionCommentL) LoadHomeworkSubmission(ctx context.Context, e boil.ContextExecutor, singular bool, maybeHomeworkSubmissionComment interface{}, mods queries.Applicator) error {
	var slice []*HomeworkSubmissionComment
	var object *HomeworkSubmissionComment

	if singular {
		object = maybeHomeworkSubmissionComment.(*HomeworkSubmissionComment)
	} else {
		slice = *maybeHomeworkSubmissionComment.(*[]*HomeworkSubmissionComment)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &homeworkSubmissionCommentR{}
		}
		args = append(args, object.HomeworkSubmissionID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &homeworkSubmissionCommentR{}
			}

			for _, a := range args {
				if a == obj.HomeworkSubmissionID {
					continue Outer
				}
			}

			args = append(args, obj.HomeworkSubmissionID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`homework_submissions`),
		qm.WhereIn(`homework_submissions.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load HomeworkSubmission")
	}

	var resultSlice []*HomeworkSubmission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice HomeworkSubmission")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for homework_submissions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for homework_submissions")
	}

	if len(homeworkSubmissionCommentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.HomeworkSubmission = foreign
		if foreign.R == nil {
			foreign.R = &homeworkSubmissionR{}
		}
		foreign.R.HomeworkSubmissionComments = append(foreign.R.HomeworkSubmissionComments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.HomeworkSubmissionID == foreign.ID {
				local.R.HomeworkSubmission = foreign
				if foreign.R == nil {
					foreign.R = &homeworkSubmissionR{}
				}
				foreign.R.HomeworkSubmissionComments = append(foreign.R.HomeworkSubmissionComments, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (homeworkSubmissionCommentL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeHomeworkSubmissionComment interface{}, mods queries.Applicator) error {
	var slice []*HomeworkSubmissionComment
	var object *HomeworkSubmissionComment

	if singular {
		object = maybeHomeworkSubmissionComment.(*HomeworkSubmissionComment)
	} else {
		slice = *maybeHomeworkSubmissionComment.(*[]*HomeworkSubmissionComment)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &homeworkSubmissionCommentR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &homeworkSubmissionCommentR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(homeworkSubmissionCommentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.HomeworkSubmissionComments = append(foreign.R.HomeworkSubmissionComments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.HomeworkSubmissionComments = append(foreign.R.HomeworkSubmissionComments, local)
				break
			}
		}
	}

	return nil
}

// SetHomeworkSubmission of the homeworkSubmissionComment to the related item.
// Sets o.R.HomeworkSubmission to related.
// Adds o to related.R.HomeworkSubmissionComments.
func (o *HomeworkSubmissionComment) SetHomeworkSubmission(ctx context.Context, exec boil.ContextExecutor, insert bool, related *HomeworkSubmission) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"homework_submission_comments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"homework_submission_id"}),
		strmangle.WhereClause("\"", "\"", 2, homeworkSubmissionCommentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.HomeworkSubmissionID = related.ID
	if o.R == nil {
		o.R = &homeworkSubmissionCommentR{
			HomeworkSubmission: related,
		}
	} else {
		o.R.HomeworkSubmission = related
	}

	if related.R == nil {
		related.R = &homeworkSubmissionR{
			HomeworkSubmissionComments: HomeworkSubmissionCommentSlice{o},
		}
	} else {
		related.R.HomeworkSubmissionComments = append(related.R.HomeworkSubmissionComments, o)
	}

	return nil
}

// SetUser of the homeworkSubmissionComment to the related item.
// Sets o.R.User to related.
// Adds o to related.R.HomeworkSubmissionComments.
func (o *HomeworkSubmissionComment) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"homework_submission_comments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, homeworkSubmissionCommentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &homeworkSubmissionCommentR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			HomeworkSubmissionComments: HomeworkSubmissionCommentSlice{o},
		}
	} else {
		related.R.HomeworkSubmissionComments = append(related.R.HomeworkSubmissionComments, o)
	}

	return nil
}

// HomeworkSubmissionComments retrieves all the records using an executor.
func HomeworkSubmissionComments(mods ...qm.QueryMod) homeworkSubmissionCommentQuery {
	mods = append(mods, qm.From("\"homework_submission_comments\""))
	return homeworkSubmissionCommentQuery{NewQuery(mods...)}
}

// FindHomeworkSubmissionComment retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindHomeworkSubmissionComment(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*HomeworkSubmissionComment, error) {
	homeworkSubmissionCommentObj := &HomeworkSubmissionComment{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"homework_submission_comments\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, homeworkSubmissionCommentObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from homework_submission_comments")
	}

	if err = homeworkSubmissionCommentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return homeworkSubmissionCommentObj, err
	}

	return homeworkSubmissionCommentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *HomeworkSubmissionComment) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no homework_submission_comments provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(homeworkSubmissionCommentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	homeworkSubmissionCommentInsertCacheMut.RLock()
	cache, cached := homeworkSubmissionCommentInsertCache[key]
	homeworkSubmissionCommentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			homeworkSubmissionCommentAllColumns,
			homeworkSubmissionCommentColumnsWithDefault,
			homeworkSubmissionCommentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(homeworkSubmissionCommentType, homeworkSubmissionCommentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(homeworkSubmissionCommentType, homeworkSubmissionCommentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"homework_submission_comments\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"homework_submission_comments\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into homework_submission_comments")
	}

	if !cached {
		homeworkSubmissionCommentInsertCacheMut.Lock()
		homeworkSubmissionCommentInsertCache[key] = cache
		homeworkSubmissionCommentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the HomeworkSubmissionComment.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *HomeworkSubmissionComment) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	homeworkSubmissionCommentUpdateCacheMut.RLock()
	cache, cached := homeworkSubmissionCommentUpdateCache[key]
	homeworkSubmissionCommentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			homeworkSubmissionCommentAllColumns,
			homeworkSubmissionCommentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update homework_submission_comments, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"homework_submission_comments\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, homeworkSubmissionCommentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(homeworkSubmissionCommentType, homeworkSubmissionCommentMapping, append(wl, homeworkSubmissionCommentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update homework_submission_comments row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for homework_submission_comments")
	}

	if !cached {
		homeworkSubmissionCommentUpdateCacheMut.Lock()
		homeworkSubmissionCommentUpdateCache[key] = cache
		homeworkSubmissionCommentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q homeworkSubmissionCommentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for homework_submission_comments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for homework_submission_comments")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o HomeworkSubmissionCommentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), homeworkSubmissionCommentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"homework_submission_comments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, homeworkSubmissionCommentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in homeworkSubmissionComment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all homeworkSubmissionComment")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *HomeworkSubmissionComment) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no homework_submission_comments provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(homeworkSubmissionCommentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	homeworkSubmissionCommentUpsertCacheMut.RLock()
	cache, cached := homeworkSubmissionCommentUpsertCache[key]
	homeworkSubmissionCommentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			homeworkSubmissionCommentAllColumns,
			homeworkSubmissionCommentColumnsWithDefault,
			homeworkSubmissionCommentColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			homeworkSubmissionCommentAllColumns,
			homeworkSubmissionCommentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert homework_submission_comments, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(homeworkSubmissionCommentPrimaryKeyColumns))
			copy(conflict, homeworkSubmissionCommentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"homework_submission_comments\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(homeworkSubmissionCommentType, homeworkSubmissionCommentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(homeworkSubmissionCommentType, homeworkSubmissionCommentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert homework_submission_comments")
	}

	if !cached {
		homeworkSubmissionCommentUpsertCacheMut.Lock()
		homeworkSubmissionCommentUpsertCache[key] = cache
		homeworkSubmissionCommentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single HomeworkSubmissionComment record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *HomeworkSubmissionComment) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no HomeworkSubmissionComment provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), homeworkSubmissionCommentPrimaryKeyMapping)
	sql := "DELETE FROM \"homework_submission_comments\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from homework_submission_comments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for homework_submission_comments")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q homeworkSubmissionCommentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no homeworkSubmissionCommentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from homework_submission_comments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for homework_submission_comments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o HomeworkSubmissionCommentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(homeworkSubmissionCommentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), homeworkSubmissionCommentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"homework_submission_comments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, homeworkSubmissionCommentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from homeworkSubmissionComment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for homework_submission_comments")
	}

	if len(homeworkSubmissionCommentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *HomeworkSubmissionComment) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindHomeworkSubmissionComment(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HomeworkSubmissionCommentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := HomeworkSubmissionCommentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), homeworkSubmissionCommentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"homework_submission_comments\".* FROM \"homework_submission_comments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, homeworkSubmissionCommentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in HomeworkSubmissionCommentSlice")
	}

	*o = slice

	return nil
}

// HomeworkSubmissionCommentExists checks if the HomeworkSubmissionComment row exists.
func HomeworkSubmissionCommentExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"homework_submission_comments\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if homework_submission_comments exists")
	}

	return exists, nil
}
