// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ChatroomEvents", testChatroomEventsUpsert)

	t.Run("ChatroomUsers", testChatroomUsersUpsert)

	t.Run("Chatrooms", testChatroomsUpsert)

	t.Run("DiaryEntries", testDiaryEntriesUpsert)

	t.Run("DiaryEntryComments", testDiaryEntryCommentsUpsert)

	t.Run("Events", testEventsUpsert)

	t.Run("LoginSessions", testLoginSessionsUpsert)

	t.Run("Messages", testMessagesUpsert)

	t.Run("SharedDiaryEntries", testSharedDiaryEntriesUpsert)

	t.Run("UserReceivedChatroomEvents", testUserReceivedChatroomEventsUpsert)

	t.Run("UserReceivedMessages", testUserReceivedMessagesUpsert)

	t.Run("Users", testUsersUpsert)
}
