// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSharedDiaryEntries(t *testing.T) {
	t.Parallel()

	query := SharedDiaryEntries()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSharedDiaryEntriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSharedDiaryEntriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SharedDiaryEntries().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSharedDiaryEntriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SharedDiaryEntrySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSharedDiaryEntriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SharedDiaryEntryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if SharedDiaryEntry exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SharedDiaryEntryExists to return true, but got false.")
	}
}

func testSharedDiaryEntriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	sharedDiaryEntryFound, err := FindSharedDiaryEntry(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if sharedDiaryEntryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSharedDiaryEntriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SharedDiaryEntries().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSharedDiaryEntriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SharedDiaryEntries().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSharedDiaryEntriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	sharedDiaryEntryOne := &SharedDiaryEntry{}
	sharedDiaryEntryTwo := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, sharedDiaryEntryOne, sharedDiaryEntryDBTypes, false, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}
	if err = randomize.Struct(seed, sharedDiaryEntryTwo, sharedDiaryEntryDBTypes, false, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sharedDiaryEntryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sharedDiaryEntryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SharedDiaryEntries().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSharedDiaryEntriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	sharedDiaryEntryOne := &SharedDiaryEntry{}
	sharedDiaryEntryTwo := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, sharedDiaryEntryOne, sharedDiaryEntryDBTypes, false, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}
	if err = randomize.Struct(seed, sharedDiaryEntryTwo, sharedDiaryEntryDBTypes, false, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sharedDiaryEntryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sharedDiaryEntryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func sharedDiaryEntryBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *SharedDiaryEntry) error {
	*o = SharedDiaryEntry{}
	return nil
}

func sharedDiaryEntryAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *SharedDiaryEntry) error {
	*o = SharedDiaryEntry{}
	return nil
}

func sharedDiaryEntryAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *SharedDiaryEntry) error {
	*o = SharedDiaryEntry{}
	return nil
}

func sharedDiaryEntryBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SharedDiaryEntry) error {
	*o = SharedDiaryEntry{}
	return nil
}

func sharedDiaryEntryAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SharedDiaryEntry) error {
	*o = SharedDiaryEntry{}
	return nil
}

func sharedDiaryEntryBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SharedDiaryEntry) error {
	*o = SharedDiaryEntry{}
	return nil
}

func sharedDiaryEntryAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SharedDiaryEntry) error {
	*o = SharedDiaryEntry{}
	return nil
}

func sharedDiaryEntryBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SharedDiaryEntry) error {
	*o = SharedDiaryEntry{}
	return nil
}

func sharedDiaryEntryAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SharedDiaryEntry) error {
	*o = SharedDiaryEntry{}
	return nil
}

func testSharedDiaryEntriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &SharedDiaryEntry{}
	o := &SharedDiaryEntry{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry object: %s", err)
	}

	AddSharedDiaryEntryHook(boil.BeforeInsertHook, sharedDiaryEntryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	sharedDiaryEntryBeforeInsertHooks = []SharedDiaryEntryHook{}

	AddSharedDiaryEntryHook(boil.AfterInsertHook, sharedDiaryEntryAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	sharedDiaryEntryAfterInsertHooks = []SharedDiaryEntryHook{}

	AddSharedDiaryEntryHook(boil.AfterSelectHook, sharedDiaryEntryAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	sharedDiaryEntryAfterSelectHooks = []SharedDiaryEntryHook{}

	AddSharedDiaryEntryHook(boil.BeforeUpdateHook, sharedDiaryEntryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	sharedDiaryEntryBeforeUpdateHooks = []SharedDiaryEntryHook{}

	AddSharedDiaryEntryHook(boil.AfterUpdateHook, sharedDiaryEntryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	sharedDiaryEntryAfterUpdateHooks = []SharedDiaryEntryHook{}

	AddSharedDiaryEntryHook(boil.BeforeDeleteHook, sharedDiaryEntryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	sharedDiaryEntryBeforeDeleteHooks = []SharedDiaryEntryHook{}

	AddSharedDiaryEntryHook(boil.AfterDeleteHook, sharedDiaryEntryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	sharedDiaryEntryAfterDeleteHooks = []SharedDiaryEntryHook{}

	AddSharedDiaryEntryHook(boil.BeforeUpsertHook, sharedDiaryEntryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	sharedDiaryEntryBeforeUpsertHooks = []SharedDiaryEntryHook{}

	AddSharedDiaryEntryHook(boil.AfterUpsertHook, sharedDiaryEntryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	sharedDiaryEntryAfterUpsertHooks = []SharedDiaryEntryHook{}
}

func testSharedDiaryEntriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSharedDiaryEntriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(sharedDiaryEntryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSharedDiaryEntryToOneDiaryEntryUsingDiaryEntry(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SharedDiaryEntry
	var foreign DiaryEntry

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, sharedDiaryEntryDBTypes, false, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, diaryEntryDBTypes, false, diaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DiaryEntry struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.DiaryEntryID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.DiaryEntry().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := SharedDiaryEntrySlice{&local}
	if err = local.L.LoadDiaryEntry(ctx, tx, false, (*[]*SharedDiaryEntry)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DiaryEntry == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.DiaryEntry = nil
	if err = local.L.LoadDiaryEntry(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DiaryEntry == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testSharedDiaryEntryToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SharedDiaryEntry
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, sharedDiaryEntryDBTypes, false, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := SharedDiaryEntrySlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*SharedDiaryEntry)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testSharedDiaryEntryToOneSetOpDiaryEntryUsingDiaryEntry(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SharedDiaryEntry
	var b, c DiaryEntry

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sharedDiaryEntryDBTypes, false, strmangle.SetComplement(sharedDiaryEntryPrimaryKeyColumns, sharedDiaryEntryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, diaryEntryDBTypes, false, strmangle.SetComplement(diaryEntryPrimaryKeyColumns, diaryEntryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, diaryEntryDBTypes, false, strmangle.SetComplement(diaryEntryPrimaryKeyColumns, diaryEntryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*DiaryEntry{&b, &c} {
		err = a.SetDiaryEntry(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.DiaryEntry != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SharedDiaryEntries[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.DiaryEntryID != x.ID {
			t.Error("foreign key was wrong value", a.DiaryEntryID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DiaryEntryID))
		reflect.Indirect(reflect.ValueOf(&a.DiaryEntryID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.DiaryEntryID != x.ID {
			t.Error("foreign key was wrong value", a.DiaryEntryID, x.ID)
		}
	}
}
func testSharedDiaryEntryToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SharedDiaryEntry
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sharedDiaryEntryDBTypes, false, strmangle.SetComplement(sharedDiaryEntryPrimaryKeyColumns, sharedDiaryEntryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SharedDiaryEntries[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testSharedDiaryEntriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSharedDiaryEntriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SharedDiaryEntrySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSharedDiaryEntriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SharedDiaryEntries().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	sharedDiaryEntryDBTypes = map[string]string{`ID`: `integer`, `Title`: `character varying`, `DiaryEntryID`: `integer`, `UserID`: `integer`, `CreatedAt`: `timestamp without time zone`}
	_                       = bytes.MinRead
)

func testSharedDiaryEntriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(sharedDiaryEntryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(sharedDiaryEntryAllColumns) == len(sharedDiaryEntryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSharedDiaryEntriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(sharedDiaryEntryAllColumns) == len(sharedDiaryEntryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SharedDiaryEntry{}
	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sharedDiaryEntryDBTypes, true, sharedDiaryEntryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(sharedDiaryEntryAllColumns, sharedDiaryEntryPrimaryKeyColumns) {
		fields = sharedDiaryEntryAllColumns
	} else {
		fields = strmangle.SetComplement(
			sharedDiaryEntryAllColumns,
			sharedDiaryEntryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SharedDiaryEntrySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSharedDiaryEntriesUpsert(t *testing.T) {
	t.Parallel()

	if len(sharedDiaryEntryAllColumns) == len(sharedDiaryEntryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SharedDiaryEntry{}
	if err = randomize.Struct(seed, &o, sharedDiaryEntryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SharedDiaryEntry: %s", err)
	}

	count, err := SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, sharedDiaryEntryDBTypes, false, sharedDiaryEntryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SharedDiaryEntry struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SharedDiaryEntry: %s", err)
	}

	count, err = SharedDiaryEntries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
